name: Release

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
          cache: true

      - name: Build and Pack
        run: |
          chmod +x pack.sh
          ./pack.sh

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pack/*
            pack.zip
          generate_release_notes: true
